language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-26.0.0
    - android-26
    - android-22
    - sys-img-x86_64-android-22
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
before_install:
 - git clone --depth=50 https://github.com/wala/WALA /tmp/WALA
install:
 - pushd /tmp/WALA
 - mvn clean install -DskipTests -B -q
 - popd
before_script:
- echo no | android create avd --force -n WalaTester -t android-22 --abi x86_64
- emulator -avd WalaTester -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
