language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-26.0.1
    - android-26
    - android-24
    - sys-img-armeabi-v7a-android-24
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
before_install:
 - echo no | android create avd --force -n WalaTester -t android-24 --abi armeabi-v7a
 - emulator -avd WalaTester -no-audio -no-window &
 - git clone --depth=50 https://github.com/wala/WALA /tmp/WALA
install:
 - pushd /tmp/WALA
 - mvn clean install -DskipTests -B -q
 - popd
before_script:
- android-wait-for-emulator
- adb shell input keyevent 82 &
