language: android
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.0
    - android-26
    - sys-img-x86_64-android-25
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
before_install:
 - git clone --depth=50 https://github.com/wala/WALA /tmp/WALA
install:
 - pushd /tmp/WALA
 - mvn clean install -DskipTests -B -q
 - popd
